version: '3'
services:
  vault:
    hostname: vault
    image: vault:latest
    cap_add:
      - IPC_LOCK
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=vaultpassword
      - VAULT_ADDR=http://127.0.0.1:8200
    ports:
      - "8200:8200"
  postgresdb:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
  vaultprep:
    hostname: vaultprep
    build: ./vaultprep
    environment: 
      - VAULT_TOKEN=vaultpassword
      - VAULT_ADDR=http://vault:8200
    depends_on:
      - vault
    command: ["python","/app/seeddata.py"]
